In [165]:
from sklearn import svm,metrics
from sklearn.model_selection import train_test_split 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import random

matplotlib.rcParams['font.family'] = 'Malgun Gothic' # 한글 설정
matplotlib.rcParams['font.size'] = 10 #글자 크기
matplotlib.rcParams['axes.unicode_minus'] = False

In [166]:
df = pd.read_csv('../z20_data/iris.csv')
df.head(3)

   SepalLength  SepalWidth  PetalLength  PetalWidth         Name
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa

In [167]:
# df.iloc[row 데이터, columns 데이터]

### train_input = rows 100개 출력
### SepalLength,SepalWidth,PetalLength,PetalWidth
train_input = df.iloc[0:100,:-1]

### test_input = rows 50개 출력
### SepalLength,SepalWidth,PetalLength,PetalWidth
test_input = df.iloc[100:,:-1]

### train_target = rows 100개 출력
### Name
train_target = df.iloc[:100,-1]

### test_target = rows 50개 출력
### Name
test_target = df.iloc[100:,-1]

In [168]:
# 1. 파이썬 random 함수 사용
ran_num = [i for i in range(150)]
random.shuffle(ran_num)
train_input = df.iloc[ran_num[:100],:-1]
train_input

# 2. numpy random 함수 사용
# (0-149) 150개 배열 생성
index = np.arange(150)
# random code 0-149 랜덤 숫자 생성
np.random.shuffle(index)
train_input = df.iloc[index[:100],:-1]
train_input

     SepalLength  SepalWidth  PetalLength  PetalWidth
114          5.8         2.8          5.1         2.4
46           5.1         3.8          1.6         0.2
105          7.6         3.0          6.6         2.1
119          6.0         2.2          5.0         1.5
69           5.6         2.5          3.9         1.1
..           ...         ...          ...         ...
112          6.8         3.0          5.5         2.1
73           6.1         2.8          4.7         1.2
132          6.4         2.8          5.6         2.2
56           6.3         3.3          4.7         1.6
34           4.9         3.1          1.5         0.1

[100 rows x 4 columns]

In [169]:
# 1. 데이터 전처리: data, result 데이터 분리
# -1). train_data, test_data 수동 분리 --> 랜덤 필요
# train_input = df.iloc[index[0:100],:-1]
# test_input = df.iloc[index[100:],:-1]
# train_target = df.iloc[index[0:100],-1]
# test_target = df.iloc[index[100:],-1]

In [170]:
# -2). train_data, test_data 자동 분리 --> 랜덤 필요X
# from sklearn.model_selection import train_test_split 
datas_input = df.iloc[:,:-1]
datas_target = df.iloc[:,4]
train_input, test_input, train_target, test_target = train_test_split(datas_input,datas_target)

In [171]:
# 2. 데이터 학습 - 모델 선정 후 데이터 훈련
clf = svm.SVC()
clf.fit(train_input,train_target) ## 데이터 훈련

# 3. 데이터 예측
result = clf.predict(test_input)

# 4. 정답률 구하기 (함수 2가지 중 하나 사용)
# score = metrics.accuracy_score(test_target,result) 
score = clf.score(test_input,test_target)
print("정답률: ", score)

정답률:  0.9473684210526315

In [172]:
df.head()

   SepalLength  SepalWidth  PetalLength  PetalWidth         Name
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [184]:
# 품종 출력
#1. 4.9,2.9,1.4,0.2 --> Iris-setosa
#2. 5.6,3,4.1,1.2 --> Iris-versicolor
#3. 6.5,2.8,6.7,2.2 --> Iris-virginica

test_input = [[4.9,2.9,1.4,0.2],[5.6,3,4.1,1.2],[6.5,2.8,6.7,2.2]]
print(test_input)
pre = clf.predict(test_input)
print('정답: ',pre)

[[4.9, 2.9, 1.4, 0.2], [5.6, 3, 4.1, 1.2], [6.5, 2.8, 6.7, 2.2]]
정답:  ['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']

c:\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(