In [147]:
import numpy as np
import pandas as pd
from tensorflow import keras

In [156]:
# keras 라이브러리에 손글씨 데이터 내장되어 있음.
(train_input, train_target),(test_input, test_target) = keras.datasets.mnist.load_data()
train_input.shape

(60000, 28, 28)

In [148]:
train_data=pd.read_csv('../z20_data/train.csv',header=None)
train_data.head(2)
test_data = pd.read_csv('../z20_data/t10k.csv', header=None)
test_data.head(2)

,0,1,2,3,4,5,6,7,8,9,...,775,776,777,778,779,780,781,782,783,784
0,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [149]:
# data, target 분리
train_input = train_data.iloc[:,1:] # 1열 삭제
train_target = train_data[0]
test_input = test_data.iloc[:,1:] # 1열 삭제
test_target = test_data[0]

In [150]:
train_input

,1,2,3,4,5,6,7,8,9,10,...,775,776,777,778,779,780,781,782,783,784
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [151]:
# 0-1까지의 값으로 변경
train_input = train_input/225
test_input = test_input/225

In [152]:
# train_scaled = train_input.to_numpy().reshape(-1,28*28)
# test_scaled = test_input.to_numpy().reshape(-1,28*28)

In [153]:
# 딥러닝 - 인공신경망 모델 
from sklearn.model_selection import train_test_split

# 딥러닝 - 훈련 세트, 검증 세트, 테스트 세트(train, val, test)
train_input, val_input, train_target, val_target = train_test_split(
    train_input, train_target, test_size=0.2, random_state=42
)

In [154]:
dense = keras.layers.Dense(10, activation='softmax',input_shape=(784,))
model = keras.Sequential([dense])
model.compile(loss='sparse_categorical_crossentropy',metrics=['accuracy'])
# default: batch_size=32(64,128)
model.fit(train_input,train_target, epochs=5)
model.evaluate(val_input,val_target)

Epoch 1/5

c:\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.2577 - loss: 2.1107
Epoch 2/5
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 636us/step - accuracy: 0.6851 - loss: 1.4153
Epoch 3/5
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7872 - loss: 1.0187
Epoch 4/5
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 642us/step - accuracy: 0.8431 - loss: 0.8098
Epoch 5/5
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 682us/step - accuracy: 0.8672 - loss: 0.6431
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 986us/step - accuracy: 0.8717 - loss: 0.6596

[0.6984858512878418, 0.8457711338996887]